# Copyright 2021 dwellir
# See LICENSE file for licensing details.
#
options:
  binary-url:
    type: string
    default: ""
    description: |
      Path to download binary or .deb file from. E.g. https://github.com/paritytech/polkadot/releases/download/v0.9.10/polkadot
      Different installation methods will depending on if the file is a .deb or not.
  binary-sha256-url:
    type: string
    default: ""
    description: |
      If the URL is provided, the charm downloads the sha256 and performs a checksum check against the binary.

      Note: needs to point to the sha256 corresponding to the 'binary-url' ahead of downloading the binary!
  docker-tag:
    type: string
    default: ""
    description: "The tag of the docker image to extract binary from. E.g. v1.5.0"
  service-args:
    type: string
    default: ""
    description: |
      Extra arguments that the service should run with.

      '--chain=... --rpc-port=...' are required to set for the charm to run.
